// ============================================================
// AntimAI — PDF Letter Generator (pdf-lib)
// ============================================================

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

const NAVY = rgb(10 / 255, 22 / 255, 40 / 255);
const ORANGE = rgb(249 / 255, 115 / 255, 22 / 255);
const DARK_GRAY = rgb(55 / 255, 65 / 255, 81 / 255);
const LIGHT_GRAY = rgb(156 / 255, 163 / 255, 175 / 255);

export async function generateLetterPdf(
  letterText: string,
  institution: string,
  heirName: string
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const timesRoman = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const timesRomanBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 595.28; // A4
  const pageHeight = 841.89;
  const margin = 60;
  const contentWidth = pageWidth - margin * 2;

  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPosition = pageHeight - margin;

  // ── Header bar ──
  page.drawRectangle({
    x: 0,
    y: pageHeight - 45,
    width: pageWidth,
    height: 45,
    color: NAVY,
  });

  page.drawText("AntimAI", {
    x: margin,
    y: pageHeight - 32,
    size: 18,
    font: helveticaBold,
    color: ORANGE,
  });

  page.drawText("Post-Death Administrative Assistant", {
    x: margin + 85,
    y: pageHeight - 30,
    size: 9,
    font: helvetica,
    color: LIGHT_GRAY,
  });

  yPosition = pageHeight - 80;

  // ── Divider line ──
  page.drawLine({
    start: { x: margin, y: yPosition },
    end: { x: pageWidth - margin, y: yPosition },
    thickness: 1,
    color: ORANGE,
  });

  yPosition -= 25;

  // ── Institution heading ──
  page.drawText(`RE: ${institution}`, {
    x: margin,
    y: yPosition,
    size: 12,
    font: timesRomanBold,
    color: NAVY,
  });

  yPosition -= 30;

  // ── Letter body ──
  const fontSize = 11;
  const lineHeight = 16;
  const lines = wrapText(letterText, timesRoman, fontSize, contentWidth);

  for (const line of lines) {
    if (yPosition < margin + 60) {
      // Add a new page
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - margin;
    }
    page.drawText(line, {
      x: margin,
      y: yPosition,
      size: fontSize,
      font: timesRoman,
      color: DARK_GRAY,
    });
    yPosition -= lineHeight;
  }

  // ── Footer ──
  yPosition -= 20;

  if (yPosition < margin + 40) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    yPosition = pageHeight - margin;
  }

  page.drawLine({
    start: { x: margin, y: yPosition },
    end: { x: pageWidth - margin, y: yPosition },
    thickness: 0.5,
    color: LIGHT_GRAY,
  });

  yPosition -= 15;

  page.drawText(
    `Generated by AntimAI — This is a draft letter. Please review before submission.`,
    {
      x: margin,
      y: yPosition,
      size: 8,
      font: helvetica,
      color: LIGHT_GRAY,
    }
  );

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}

/**
 * Word-wrap text to fit within a given width using the font metrics.
 */
function wrapText(
  text: string,
  font: { widthOfTextAtSize: (text: string, size: number) => number },
  fontSize: number,
  maxWidth: number
): string[] {
  const paragraphs = text.split("\n");
  const result: string[] = [];

  for (const paragraph of paragraphs) {
    if (paragraph.trim() === "") {
      result.push("");
      continue;
    }

    const words = paragraph.split(/\s+/);
    let currentLine = "";

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      try {
        const testWidth = font.widthOfTextAtSize(testLine, fontSize);
        if (testWidth > maxWidth && currentLine) {
          result.push(currentLine);
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      } catch {
        // If width calculation fails, use character-based estimation
        if (testLine.length * fontSize * 0.5 > maxWidth && currentLine) {
          result.push(currentLine);
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      }
    }

    if (currentLine) {
      result.push(currentLine);
    }
  }

  return result;
}
